version: '3'

services:
  db:
    image: postgres:latest
    container_name: my-db-docker
    ports:
      - 54321:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

  pg-admin:    
    image: dpage/pgadmin4:latest    
    container_name: pg-admin-docker    
    ports:       
      - 4433:443       
      - 8080:80    
    environment:      
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}      
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}  

  strapi:
    platform: linux/amd64 
    image: naskio/strapi:latest    
    container_name: my-app-docker    
    ports:      
      - 1337:1337    
    environment:      
      - DATABASE_HOST=${DATABASE_HOST}     
      - DATABASE_NAME=${DATABASE_NAME}      
      - DATABASE_USERNAME=${DATABASE_USERNAME}      
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}      
      - DATABASE_PORT=${DATABASE_PORT}      
      - DATABASE_SSL=false      
      - DATABASE_CLIENT=postgres
      
 
    

